[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
sqlx = { version = "0.8.5", features = ["sqlite", "runtime-tokio-rustls", "macros"] }
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
